---
- name: Create ansible user and copy SSH key
  hosts: all
  become: true
  vars:
    ansible_user_name: ansible
    ansible_pub_key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

  tasks:
    - name: Ensure the ansible user exists
      user:
        name: "{{ ansible_user_name }}"
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh directory for ansible user
      file:
        path: "/home/{{ ansible_user_name }}/.ssh"
        state: directory
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: '0700'

    - name: Add public key to authorized_keys
      copy:
        content: "{{ ansible_pub_key }}"
        dest: "/home/{{ ansible_user_name }}/.ssh/authorized_keys"
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: '0600'
